version: "3"
name: mb-static

services:
  node:
    container_name: mb-static-js-build
    restart: no
    build:
      context: .
      dockerfile: node/Dockerfile
    command:
      - /bin/bash
      - -c
      - |
        npm install
        npm run build
    working_dir: /var/www/src
    volumes:
      - ../website:/var/www/src

  nginx:
    container_name: mb-static-nginx
    depends_on:
      - node
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: always
    tty: true
    ports:
      - ${PORT_WEBSITE}:3000
    volumes:
      - ../website:/var/www/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
